### ISSUE TITLE
Mir does not support xdg-shell-v5

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1008]
On 16.04LTS GTK3+ tries to use xdg-shell-v5 and, as Mir does not support this, GTK applications crash on startup.

With [UBports starting to use Wayland on 16.04LTS](https://forums.ubports.com/topic/3158/continuation-of-rpi-effort-and-how-to-test) they've hit this.

The differences between xdg-shell-v6 and xdg-shell-v5 are trivial. This is something someone in "the community" could tackle with a mostly copy/paste/rename exercise (and do the necessary testing on 16.04 desktop).

**Comment by keithbowes** [comment]
Though, xdg_shell_v5 and xdg_shell stable (which is [supported by Mir]( https://discourse.ubuntu.com/t/xdg-shell-stable-supported-by-mir/7492)) are incompatible, so suffice it to say v5 won't be supported at all (it would mean ripping out the code for xdg_shell stable just to placate users of a crufty LTS release).  I can only imagine how old the version of GTK would have to be to use xdg_shell_v5, when v6 was introduced in 2015.

**Comment by RAOF** [comment]
It would actually not be difficult to support v5, v6 and _stable; we already support v6 and _stable, so it would not require ripping out any existing support, just adding a new implementation of some existing interfaces.

As you say, v5 is *somewhat old*, so it's not something we're likely to prioritise (which is why this has the “help wanted” tag), but we'd happily accept a PR that implemented it *and* such a PR would be fairly easy to do (which is why this has the “good first issue” tag :grin: ).

**Comment by AlanGriffiths** [comment]
Nobody cares
