### ISSUE TITLE
Unbundle and separately release wlcs

### ISSUE THREAD

**Issue by Conan-Kudo** [MirServer/mir#106]
Currently, Mir bundles and builds [wlcs](https://github.com/MirServer/wlcs). It'd be great if this can be rectified so that wlcs can be shipped as a proper shared test suite for Wayland compositors to use.

**Comment by AlanGriffiths** [comment]
I was thinking about that too after I encountered #104

**Comment by Saviq** [comment]
There's certainly arguments for and against. The maintenance burden of another tarball, packaging, version syncing is significant. If the problem is github's releases, that's solved by us uploading a real tarball automagically to github. It's never going to be a runtime library, always a build/test time thing. So I'm not certain it's worth the effort. @RAOF wdyt?

**Comment by AlanGriffiths** [comment]
@Saviq problems can be expected if several Wayland implementations build and ship their own "libwlcs.so".

There are several solutions:
1. rename the .so for each compositor
2. statically link to the tests of each compositor
3. bundle it separately

**Comment by RAOF** [comment]
@Saviq I always intended wlcs to eventually be unbundled and installable separately; that's why it's in a separate git repository.

I don't think it currently makes sense to ship, though.

**Comment by AlanGriffiths** [comment]
@camako we're (finally) in the process of splitting wlcs out as a package in its own right. https://github.com/MirServer/wlcs/pull/71

**Comment by AlanGriffiths** [comment]
Done: https://github.com/MirServer/wlcs/releases/tag/v1.0.0
