### ISSUE TITLE
Frame events are not sent until/unless buffers are composited

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#1377]
I think this is the cause of #1100, and the underlying cause of the symptoms seen in #1338

Re #1100: with Mir as the host server, we don't send the frame callback until we bind the texture when compositing the buffer for the first time. That throttles the nested compositor as it does not render the next frame until this happens.

Re #1338: when the host is rendering in "clone" mode, one of the fullscreen surfaces from the nested server obscures the other. The latter is never composited and so never sends a frame event which blocks the nested compositor.

**Comment by AlanGriffiths** [comment]
This seems closely related to the fragile `bind()` logic I recently made threadsafe (#1356).

We're likely giving `bind()` too much responsibility, Vis:
1. uploading the texture on first use;
2. calling `glBindTexture()`; and,
3. sending the frame event.

**Comment by RAOF** [comment]
I agree that we're giving `bind` too many responsibilities; it was a convenient place to modify, but not necessarily the most correct.

However, I think any replacement mechanism should have approximately the same behaviour - the purpose of the frame callback is to notify the client when we want another buffer from them.

The scenario in #1338 (a fully occluded surface) is explicitly called out as a case where a frame event is not expected to be sent; the nested server needs to handle this case.

**Comment by AlanGriffiths** [comment]
Clearly we should discuss further but, as a data point, using Mutter as the host doesn't exhibit these problems.

**Comment by RAOF** [comment]
It's perfectly *conformant* to immediately send frame events, or to send frame events for offscreen surfaces; you'll just be wasting CPU and GPU time getting clients to render frames that will never be displayed.

It would not immensely surprise me if there's low hanging fruit in Mutter around this :wink:

**Comment by RAOF** [comment]
For something more constructive:

Sending frame notifications at the best time requires predicting the future - the *best* time to send a frame notification is just in time for a client to render its next frame and submit it just before we begin rendering a frame.

Thus, we're never going to get it perfect, and progressive improvements in the heuristics will require information from progressively more Mir subsystems.

Currently we drive this from `Texture::bind()`; that was convenient because it needed no changes in any other part of Mir. It's not *terribly* incorrect - once we've rendered out of *this* frame there's a good chance we'll want a new frame soon (this will break as soon as we try and enable composition-bypass for Wayland clients, of course, but *that's* a not-yet-solved-in-protocol problem).

A better place to drive this would be from the `BufferStream` - that is already in charge of ensuring that there's a buffer available at all times.

Alternately, and more invasively, we could have some new code solely responsible for managing frame callbacks; this would need visibility into (at least) the rendering loop and the Wayland front end, but would make the frame decisions (and where to improve them) more obvious.

**Comment by AlanGriffiths** [comment]
To summarize discussions and investigations.

1. The right time to send frame events is _after_ compositing, giving the client just enough time to submit a buffer for the next composition pass.

> Re #1100: with Mir as the host server, we don't send the frame callback until we bind the texture when compositing the buffer for the first time. That throttles the nested compositor as it does not render the next frame until this happens.

The point of these notifications is to throttle the client: the nested compositor should only be submitting a "display" buffer after the previous one has been compositing. That this doesn't happen with Mutter or Xorg as the host isn't our problem.

> Re #1338: when the host is rendering in "clone" mode, one of the fullscreen surfaces from the nested server obscures the other. The latter is never composited and so never sends a frame event which blocks the nested compositor.

This too is a problem in the nested server. We shouldn't be configuring our "outputs" so that one is obscured, not should rendering on one block rendering on the other.
