### ISSUE TITLE
Qt/gstreamer in a snap not detecting the platform

### ISSUE THREAD

**Issue by conklinsys** [MirServer/mir#2003]
We have a Qt/gstreamer application that runs fine on 20.04 X, fine on 20.04 on Wayland, but fails in the snap in mir-kiosk.  It appears to know that it's on wayland, but is not detecting the platform

INFO               qtglutility gstqtglutility.cc:70:gst_qt_get_gl_display: QGuiApplication::instance()->platformName() wayland
ERROR            qtglutility gstqtglutility.cc:195:gst_qt_get_gl_wrapcontext: Unknown platform
INFO               gldisplay gstgldisplay.c:284:gst_gl_display_new: creating a display, user choice:(NULL) (platform: (NULL))

Is there something extra we need to configure to have it recognize as wayland?

(gstreamer 1.16.2, 20.04 in the snap)

**Comment by Saviq** [comment]
Hi @conklinsys, if I read this right, the snap is missing the platform? Like, it knows it _should_ use `wayland` (by name), but doesn't know that platform (which usually means whatever platform bits are required are missing from the snap).

**Comment by conklinsys** [comment]
The snap is otherwise an otherwise happy wayland kiosk app that runs fine.  It's more like the 20.04 qt+gstreamer plugin  isn't recognizing it as wayland.

**Comment by AlanGriffiths** [comment]
@conklinsys unfortunately the way things are in snapd means that your snap needs to be configured slightly differently to run as a `daemon`. We aim to change this, but that doesn't help you right now.

There is a tutorial for creating a "kiosk" snap here: https://ubuntu.com/tutorials/wayland-kiosk

I'm closing this issue as this is clearly not something that can be addressed in Mir.

**Comment by daleknauss** [comment]
@AlanGriffiths can you please explain your comment a little bit more? The UI currently runs as a daemon within our snap (using the mir-kiosk snap) and works fine in all other ways. It's only with this added functionality trying to instantiate gstreamer outside of QT's built in method of doing it what we run into issues.

We believe we've tracked the issue down to Mir as being the reason we're unable to get this to work. What do you mean when you say this can't be addressed in Mir?

**Comment by Saviq** [comment]
@daleknauss are you certain, when running on 20.04 Wayland, it doesn't go through the XWayland fallback? It's enabled by default in GNOME on Wayland. Unsetting `DISPLAY`, or setting it to a bogus value, when running your app, should make it clearer.

Mir should not be able to cause the reported errors…

**Comment by AlanGriffiths** [comment]
@daleknauss looking at the error messages in the original post your gstreamer app is failing to find a "wayland" platform. It needs to do that before it can attempt to connect to the Wayland socket (which it needs to do before Mir is involved).

I can speculate that this platform will be a shared library and that this is either missing from the snap or not in the place gstreamer is looking. It either needs adding to the snap, or you need to configure gstreamer to look where it is.

As @Saviq says, when run on your GNOME/Wayland desktop you might find that your gstreamer app is actually using X11. But you might also find that it works when unconfined because it can use the "wayland" platform from host system.

You could test this with Mir using the "egmde" snap. Install and this on a system where you app works on the GNOME/Wayland as follows:
```
snap install --edge egmde
egmde
```
Now, in the Mir-on-X window start your application (you can get a terminal with `Ctrl-Alt-Shift-T` and run it from there as you do from GNOME/Wayland. That will show it working on Mir.

Next, disable the X11 support in egmde by editing `~/.config/egmde.config` and commenting out the X11 support:
```
# Setup support for X11 apps (comment out to disable)
#enable-x11=
#xwayland-path=/snap/egmde/current/usr/bin/Xwayland
```
Close egmde and repeat the test.

This will show whether you are accidentally using X11 (it will now fail) or, if your app does work, that it works on Mir if it can find it's "wayland" platform.

HTH
