### ISSUE TITLE
The Wayland generator produces dubious "enums"

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2195]
In most places it doesn't matter, but there are places where _definitions_ are needed for the static date members used in generated "enums":
```c++
    struct Axis
    {
        static uint32_t const vertical_scroll = 0;
        static uint32_t const horizontal_scroll = 1;
    };
```

This only produces declarations for the "enum" members. Some contexts (e.g. taking the address or a reference) also require a definition.

(It would probably have been a better choice to use something like `enum class` and https://www.justsoftwaresolutions.co.uk/cplusplus/using-enum-classes-as-bitfields.html, but that opportunity may have passed.)

**Comment by wmww** [comment]
I looked into doing it with enum class. implementation isn't that hard, but the problem is protocols often don't tag message arguments with the enums they use. Tagging enums is possible, but even in wayland.xml the various events and requests of `wl_data_offer` and `wl_data_source` do not have tagged enums. Without protocol support or some other way for the generator to determine the type, introducing any sort of type "safety" will just introduce tons of ugly conversions and not actually improve safety significantly.
