### ISSUE TITLE
Too easy to send unsupported events

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#2343]
If a client binds to a version of a protocol that is older than what we support, sending newer events will generally crash the client. We should not do this. As #2341 demonstrates it is quite easy to do this accidentally. We should consider changing the generated code to either make this harder, or make it harmless.

**Comment by wmww** [comment]
What are the stability considerations @AlanGriffiths? can we break generated API?

**Comment by RAOF** [comment]
In a narrow sense, it seems this could be solved pretty easily at the generator level, by calling `version_supports_foo()` in the `send_foo()` implementation and only actually sending `foo` for supported versions.

This fixes the simple “we immediately crash applications binding old versions” case, but can't handle a more complex case where logic needs to change based on version rather than just not sending events.

That said, I can't think off-hand of a protocol where we need different logic based on bound version, rather than just not sending events? Maybe the simple thing is sufficiently useful?

**Comment by AlanGriffiths** [comment]
> In a narrow sense, it seems this could be solved pretty easily at the generator level, by calling `version_supports_foo()` in the `send_foo()` implementation and only actually sending `foo` for supported versions.

Agreed this doesn't cover all cases, but I think we decided to do this previously.
