### ISSUE TITLE
Allow WlSubsurfaces to be placed explicitly relative to hierarchy

### ISSUE THREAD

**Issue by fredldotme** [MirServer/mir#2487]
Wayland has some protocols to handle the explicit placement of WlSubsurfaces:
- above or below siblings
- even above or below the parent surface

I've started implementing a change for the first use-case since, as far as I see, making it work with the parent surface would involve at least sneaking another dummy WlSurface in between. I believe even Weston does something similar to that.

The initial change is here. I've not opened a PR yet since I would like to get some input around the big picture before continuing with this. Details can still be talked about in a PR.

https://github.com/fredldotme/mir-experimental/commit/ed3c67e51fc3be9f368cfab56276b6a6394c28c3

**Comment by wmww** [comment]
Hi, sorry for not getting back sooner.

Here are some notes: 
- I don't see the implementation of the new `set_subsurface()` method
- `move_child_above_sibling()`/`*_below_*` seem a bit complicated and verbose, but maybe there's not a simpler way.
- I don't see where the new `parent` member is being initialized (and thus why it needs to be a unique_ptr with a custom deleter).

If you're interested in getting this into upstream Mir, I encourage you to open a draft PR based on current main for easier review (the parent of the linked commit seems to be originally from 2020). I don't think much has changed in the subsurface code since then so hopefully that will not be hard.

**Comment by fredldotme** [comment]
- That one is right in the header. Can put it in the .cpp if preferred.
- Agreed
- `parent` is initialized somewhere else, but we need it to get to the siblings which is why I turned it into a public member. If preferred I can also try keeping the `parent` private and find a way to get to the siblings more easily.

This is actually something I'm working on for Waydroid on Ubuntu Touch, which is why this is based on 1.x still. My goal is to let it trickle down from 2.x to 1.x finally, but I need something to test it with.

If the general approach is fine I will go on and make it ready for 2.x.

**Comment by wmww** [comment]
I took a stab at implementing this, see #2491.

**Comment by wmww** [comment]
Dup of #345.
