### ISSUE TITLE
bypass only works with DMABufBuffer

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2818]
It would be more useful if it worked with ShmBuffer (e.g. glmark2-wayland uses shm)

```c++
            auto dmabuf_image = dynamic_cast<mg::DMABufBuffer*>(bypass_buffer->native_buffer_base());
            if (dmabuf_image &&
                bypass_buffer->size() == surface.size())
```

Is there a technical limitation here? Or just legacy?

**Comment by RAOF** [comment]
Kind of a bit of both?

`DMABufBuffer`s are easy to bypass with - they're already handles to GPU memory, we just need to get the driver to associate a framebuffer handle with them in order to submit them to scanout.

`ShmBuffer`s aren't in GPU memory. To scanout of them we'd need to create a DRM dumb buffer, map it, `memcpy` the content of the `ShmBuffer` into the dumb buffer, *then* get the driver to associate a fb handle with it.

This is absolutely possible, and it's *probably* still faster than GL compositing, but it's not a *clear* win - the GPU driver can plausibly use GPU hardware resources for memcpy, will likely be able to handle cache invalidation better, and so on.
