### ISSUE TITLE
Set the logind session type when mir is starting

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2833]
[From @z3ntu via telegram]

Would it be possible for Mir to set the logind session type when mir is starting? Kind of like this? Currently in some setups (e.g. postmarketOS with "autologin"+tinydm) the session type stays Type=unspecified which breaks some stuff (in this case repowerd). I guess kind of like https://github.com/swaywm/wlroots/pull/2304/files ?

(for anyone reading along, apparently repowerd essentially refuses to function if the logind session type is not "mir" or "wayland" so e.g. changing screen brightness just doesn't work without really a trace what's going on https://gitlab.com/ubports/development/core/repowerd/-/blob/main/src/adapters/logind_session_tracker.cpp#L45)

**Comment by AlanGriffiths** [comment]
I had a brief look at implementing this, but I couldn't figure out where we source `logind-session.xml` from as that needs updating to include the `SetType` functionality.

**Comment by z3ntu** [comment]
Updating the interface is the easiest exercise :wink: 

[0001-Update-logind-session.xml-from-latest-systemd.patch.txt](https://github.com/MirServer/mir/files/10732747/0001-Update-logind-session.xml-from-latest-systemd.patch.txt)
[0002-Regenerate-logind-session.-files.patch.txt](https://github.com/MirServer/mir/files/10732748/0002-Regenerate-logind-session.-files.patch.txt)

Haven't looked further into it.

**Comment by RAOF** [comment]
So, on a desktop system the display manager would be the component that creates the session that Mir is spawned in; making tinydm set the session type appropriately on construction would solve your problem.

(It's also reasonable for Mir to set this, so the PR is welcome)

**Comment by z3ntu** [comment]
We're using "autologin" before tinydm is running.

Autologin starts the logind session https://git.sr.ht/~kennylevinsen/autologin/tree/master/item/main.c#L103
But at this stage it doesn't know what session type it's going to launch. Then in tinydm we will know what it is https://gitlab.com/postmarketOS/tinydm/-/blob/master/tinydm-run-session.sh#L53 but I don't think that we can set the logind type at this stage, since we don't do the `TakeControl` call in logind and it looks like only after that is called you can set the type, at least via the dbus call `SetType`.
