### ISSUE TITLE
Alt key often getting stuck after Alt+Tab

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2946]
Every few uses of Alt+Tab, my Alt state gets stuck and I need to kick it to go back to off. The obvious symptom is that app menus drop down upon pressing the associated letter key.

**Comment by mattkae** [comment]
This should have been fixed by https://github.com/MirServer/mir/pull/2989 as part of [this ticket](https://github.com/MirServer/mir/issues/2985). I have verified that it happens - especially with Firefox - before the change, and not ever after. I can only assume that this was the original culprit :+1:

**Comment by Saviq** [comment]
Fixed by #2989
