### ISSUE TITLE
Display scaling is broken post platform refactor

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#3103]
It doesn't crash on Qemu, but still doesn't work correctly:

![imagen](https://github.com/MirServer/mir/assets/105285003/21bbc5b9-b50f-46a3-9491-770a976c21e0)

_Originally posted by @sergio-costas in https://github.com/MirServer/mir/issues/3095#issuecomment-1781180159_

**Comment by Saviq** [comment]
Another failure mode is cropping:

![obraz](https://github.com/MirServer/mir/assets/231077/77dfefee-c73d-4967-85ee-f96fad3faddf)
![obraz](https://github.com/MirServer/mir/assets/231077/ba63e508-56df-4335-9c32-c6da0cc8a71c)

**Comment by Saviq** [comment]
A simple `miral-shell --display-scale=`… makes it clear it's not an auto-scale problem.

Also using a `--display-config=static=` exhibits the same.

Using a scale > 1 doesn't render at all, and with < 1 things are rendered wrong.

**Comment by mattkae** [comment]
**Live Thoughts**
I am focusing on the gbm-kms platform for testing
- The `area` sent to `DisplayBuffer` matches the size provider. So if we're on a 1980x1080 resolution with a scale of 0.75, we'll get 2560x1440.

**Comment by AlanGriffiths** [comment]
@mattkae your comment sounds confused.

1. The number of pixels on the screen always matches the display buffer because physics. So on a 1920x1080 output that must be the size of the display buffer
2. Wayland only supports integer scaling. So for any scaling not greater than 1 the client will see a scale of 1 (and the compositor handles the rest. Similarly between 1 and 2, the scale will be reported as 2

The only way any scale comes into the size of the screen is that if we are hosted on Wayland and an output is scaled by the host, we need to know the scale to work out the number of real pixels and to submit buffers of the correct scale. (But that host scale has nothing to do with our scaling,)

**Comment by mattkae** [comment]
> @mattkae your comment sounds confused.
> 
>     1. The number of pixels on the screen always matches the display buffer because physics. So on a 1920x1080 output that must be the size of the display buffer
> 
>     2. Wayland only supports integer scaling. So for any scaling not greater than 1 the client will see a scale of 1 (and the compositor handles the rest. Similarly between 1 and 2, the scale will be reported as 2
> 
> 
> The only way any scale comes into the size of the screen is that if we are hosted on Wayland and an output is scaled by the host, we need to know the scale to work out the number of real pixels and to submit buffers of the correct scale. (But that host scale has nothing to do with our scaling,)

1. So should that `area` that's being passed to the DisplayBuffer always be 1920x1080 in that situation, instead of the scaled size of 2560x1440? That's the part that seems wrong on our end
2. Okay that makes sense to me :+1:

**Comment by RAOF** [comment]
Ah, ok.

So, this seems to work OK on X11, but I think that's a false-negative because of how the display works there.

On gbm-kms, we're allocating the FB with the *logical* size, not the physical size:
```
Oct 27 10:14:38 Swordfish kernel: i915 0000:00:02.0: [drm:drm_framebuffer_check_src_coords [drm]] Invalid source coordinates 3840.000000x2160.000000+0.000000+0.000000 (fb 1920x1080)
```

Hah! My initial interface for this would have made it impossible to allocate the wrong sized buffer for a display, but that was annoying to implement :woman_facepalming: .

Let's see where this goes wrong...

**Comment by sergio-costas** [comment]
I *have* to put this: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143/diffs

(fractional scaling support for Wayland O:-) )

**Comment by AlanGriffiths** [comment]
> (fractional scaling support for Wayland O:-) )

Thanks. I am aware of that Wayland extension, but we've not caught up and implemented it yet.

Sorry if I gave the impression that I think there is no Wayland extension for it. Was just shorthand for what we currently support.

**Comment by sergio-costas** [comment]
Sorry... I put it more like a joke. I was completely sure that you already knew about it O:-)
