### ISSUE TITLE
Mir crashes when given null argv

### ISSUE THREAD

**Issue by wmww** [MirServer/mir#578]
Specifically, it crashes here: https://github.com/MirServer/mir/blob/2ec39468c9ef6f9150f7cf8584d65018426d7a7e/src/miral/runner.cpp#L52

The reason I bring this up is because I hit this as a user of Mir, and it wouldn't have been a great experience if I wasn't a Mir dev. I don't know why Mir *needs* command line arguments, but if it does we might at least want a helpful error message.

**Comment by AlanGriffiths** [comment]
Don't get too elaborate: argv, for main(), is documented as a nullptr terminated array of pointers. That is:

    assert(argv[argc] == nullptr);

And, again for main(), the first element is always set. (Because, unlike C, you can't call main() in C++).

    assert(argc > 0);

I don't think it unreasonable to expect the same here.

Just call `mir::fatal_error()` if these preconditions are false.

**Comment by wmww** [comment]
Oh, I didn't realize argv was suppose to be null terminated. I might still make a PR, but that does make the current behavior sound a lot more reasonable.
